kind: Service
apiVersion: v1
metadata:
  name: ingress-nginx-tool
  namespace: ingress-nginx-tool
  labels:
    app.kubernetes.io/name: ingress-nginx-tool
    app.kubernetes.io/part-of: ingress-nginx-tool
  annotations:
    service.kubernetes.io/qcloud-loadbalancer-internal-subnetid: subnet-1ufupe41
    service.kubernetes.io/tke-existed-lbid: lb-ka1pczuz
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: ingress-nginx-tool
    app.kubernetes.io/part-of: ingress-nginx-tool
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
---
apiVersion: v1
kind: Service
metadata:
  name: default-http-backend
  namespace: ingress-nginx-tool
  labels:
    app: default-http-backend
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: default-http-backend
